using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Optimization;
using System.Web.Services.Description;
using System.Web.UI;
using System.Web.UI.WebControls;
using VerleihProjekt.Klassen;
using WebGrease.Activities;

namespace VerleihProjekt
{
    public partial class LeihMaterial : System.Web.UI.Page
    {
      
        protected void Page_Load(object sender, EventArgs e)

        {

             
            if (!IsPostBack)
            {
                if (Session["Kundennummer"] == null)
                {
                    //  für die Session-Variable 
                    Session["Kundennummer"] = Session["Kundennummer"]; // Beispielwert
                }
            }


            


            if (Session["LoginKonto"] == null)
            {
                Response.Redirect("Login.aspx");
            }

            bool isAdmin = (Boolean)Session["Admin"]; // 1=f 0 = t
            
            if (!isAdmin) // true 
            {
                LeihMaterialData.Visible = false;
                LeihMaterialData.Style.Value = "Display:none;";
                mErrorText.Text = "Sie haben keinen Zugriff auf diese Seite!";
                mErrorText.Visible = true;  
              
            }
            
            SDB SDBlm = new SDB();
           
            List<Leihmaterial> LeihmaterialList2 = SDBlm.GetLeihmaterial(); 
            LeihmaterialData2.DataSource = LeihmaterialList2;
            LeihmaterialData2.DataBind();

            //Notizen über Gridviews und wie man Zeilen bedingt färben kann:
            // LeihmaterialData.RowStyle.
            //LeihmaterialData.AllowSorting = true;
            //LeihmaterialData.AutoGenerateDeleteButton = true;
            //LeihmaterialData.PageSize = 1;
            //LeihmaterialData.PagerStyle.Width = 10;
            //LeihmaterialData.PagerStyle.BorderColor=global::System.Drawing.Color.White;
            //LeihmaterialData.PagerStyle.BackColor=global::System.Drawing.Color.Red;
            //// LeihmaterialData.PageSize = LeihmaterialList.Count;
            //LeihmaterialData.Style = "";


            /*        Invnr     Modell    Farbe  
             ROW(0):  CELL(0)   CELL(1)   CELL(2)
             ROW(1):  CELL(0)   CELL(1)   CELL(2)
             ROW(2):  CELL(0)   CELL(1)   CELL(2)
             ROW(3):  CELL(0)   CELL(1)   CELL(2)
             ROW(4):  CELL(0)   CELL(1)   CELL(2) */

            /*  LeihmaterialData.Rows[5].Cells[1].ColumnSpan = 5;
             // LeihmaterialData.Rows[i].Cells[2].BorderColor.
              Response.Write(LeihmaterialData.Rows[1].Cells[2].Text);
              Response.Write(LeihmaterialData.Rows[ 3].Style);
              LeihmaterialData.Rows[15].Cells[1].BackColor=global::System.Drawing.Color.Green;
              for (int i = 0; i < LeihmaterialList.Count; i++) {
                  if (LeihmaterialData.Rows[i].Cells[2].Text == "Rot")
                  {
                      LeihmaterialData.Rows[i].Cells[2].BackColor = global::System.Drawing.Color.Red;
                  }

                  switch (LeihmaterialData.Rows[i].Cells[2].Text)
                  {
                      case "Schwarz":
                          LeihmaterialData.Rows[i].Cells[2].BackColor = global::System.Drawing.Color.Black;
                          break;
                      case "Silber":
                          LeihmaterialData.Rows[i].Cells[2].BackColor = global::System.Drawing.Color.Silver;
                          break;
                      case "Blau":
                          LeihmaterialData.Rows[i].Cells[2].BackColor = global::System.Drawing.Color.Blue;
                          break;

                      case "Grau":
                          LeihmaterialData.Rows[i].Cells[2].BackColor = global::System.Drawing.Color.Gray;
                          break;
                      default:
                          break;
                  }
                  LeihmaterialData.Rows[i].Cells[2].Text = "";

                  if (i + 1 < LeihmaterialData.Rows.Count)
                  {
                      if (LeihmaterialData.Rows[i].Cells[1].Text != LeihmaterialData.Rows[i + 1].Cells[1].Text)
                      {
                          LeihmaterialData.Rows[i + 1].CssClass = "End";
                          LeihmaterialData.Rows[i + 1].Style.Value = "border-top: solid 2px black;";
                      }
                  }

              }
            in js: 
              /*
        //let td = document.querySelectorAll("td"); // ich will ducrh alle tds loopen, // ne das hat leider nicht funktioniert, ich habe recharchiert darüber  und es scheint nicht so einfach zu sein!
        //for (let a = 0; a < td.length; a++) {
        //    if (td[a].innerText == "Rot")
        //        td[a].style.background = "red";
        //}*/

            

           

        }


        protected void LeihmaterialData2_DataBound(Object sender, EventArgs e)
        {
            if (!IsPostBack)
            {
                // Call a helper method to display the current page number 
                // when the page is first loaded.
                DisplayCurrentPage();
            }
        }

        protected void LeihmaterialData2_PageIndexChanged(Object sender, EventArgs e)
        {
            // Call a helper method to display the current page number 
            // when the user navigates to a different page.

           DisplayCurrentPage();
        }
     
        void DisplayCurrentPage()
        {
            
            // Calculate the current page number.
            int currentPage = LeihmaterialData2.PageIndex + 1;

            // Display the current page number. 
           
            
                Message.Text = "Seite " + currentPage.ToString() + " von " +
                  LeihmaterialData2.PageCount.ToString() + ".";
              
        }

        protected void LeihmaterialData2_PageIndexChanging(Object sender, GridViewPageEventArgs e)
        {
            LeihmaterialData2.PageIndex = e.NewPageIndex;
            
            // Cancel the paging operation if the user attempts to navigate
            // to another page while the GridView control is in edit mode. 
            if (LeihmaterialData2.EditIndex != -1)
            {
                // Use the Cancel property to cancel the paging operation.
                e.Cancel = true;

                // Display an error message.
                int newPageNumber = e.NewPageIndex + 1;
                Message.Text = "Please update the record before moving to page " +
                  newPageNumber.ToString() + ".";
            }
            else
            {
                // Clear the error message.
                Message.Text = "";
                this.DisplayCurrentPage();
            }

        }

       protected void LeihmaterialData2_RowCancelingEdit(Object sender, GridViewCancelEditEventArgs e)
        {
            // Clear the error message.
            Message.Text = "";
        }
        protected void SqlDataSource1_Selected(object sender, SqlDataSourceStatusEventArgs e)
        {

            if (e.ExceptionHandled)
            {

                Message.Text = "There is a problem";

            }
        }
        protected void SqldsExample_Selecting(object sender, SqlDataSourceCommandEventArgs e)
        {
           
            //Projekt.SelectCommand = "SELECT L.*, R.Leihbeginn, R.Leihende FROM LEIHMATERIAL L";
            // Projekt.SelectCommand += "INNER JOIN RESERVIERUNG R ON R.Inventarnummer = L.Inventarnummer";
            //  Projekt.SelectCommand += "WHERE R.Kundennummer = @Kundennummer";
            //  e.Command.Parameters["@Kundennummer"].Value = Session["Kundennummer"];
        }

        


        protected void Projekt_Selected(object sender, SqlDataSourceStatusEventArgs e)
        {
            if (e.Exception != null)
            {
                mErrorText.Text = e.Exception.Message;
                mErrorText.Visible = true;
                e.ExceptionHandled = true;
            }
        }

    }
}